package com.cty.purduecomm.gateway.infrastructure.persistant.dataobject;

import java.util.Date;

public class AuthUserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.access_token
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.biz_user_id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private String bizUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.biz_type
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private Byte bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.created_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.last_modified_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    private Date lastModifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.id
     *
     * @return the value of auth_user.id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.id
     *
     * @param id the value for auth_user.id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.access_token
     *
     * @return the value of auth_user.access_token
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.access_token
     *
     * @param accessToken the value for auth_user.access_token
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.biz_user_id
     *
     * @return the value of auth_user.biz_user_id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public String getBizUserId() {
        return bizUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.biz_user_id
     *
     * @param bizUserId the value for auth_user.biz_user_id
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setBizUserId(String bizUserId) {
        this.bizUserId = bizUserId == null ? null : bizUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.biz_type
     *
     * @return the value of auth_user.biz_type
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.biz_type
     *
     * @param bizType the value for auth_user.biz_type
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.created_date
     *
     * @return the value of auth_user.created_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.created_date
     *
     * @param createdDate the value for auth_user.created_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.last_modified_date
     *
     * @return the value of auth_user.last_modified_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public Date getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.last_modified_date
     *
     * @param lastModifiedDate the value for auth_user.last_modified_date
     *
     * @mbg.generated Sat Jun 22 09:36:12 CST 2019
     */
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
}