server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.1.4:30000/auth/realms/myapp
#            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: standard-client
            client-secret: none
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: recource
          uri: http://localhost:8090
          predicates:
            - Path=/resource