package com.cty.purduecomm.gateway.infrastructure.persistant.mapper;

import com.cty.purduecomm.gateway.infrastructure.persistant.dataobject.AuthUserDO;
import com.cty.purduecomm.gateway.infrastructure.persistant.dataobject.AuthUserDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthUserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    long countByExample(AuthUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int deleteByExample(AuthUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int insert(AuthUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int insertSelective(AuthUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    List<AuthUserDO> selectByExample(AuthUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    AuthUserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") AuthUserDO record, @Param("example") AuthUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int updateByExample(@Param("record") AuthUserDO record, @Param("example") AuthUserDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int updateByPrimaryKeySelective(AuthUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Fri Jun 21 23:27:45 CST 2019
     */
    int updateByPrimaryKey(AuthUserDO record);
}