server:
  port: 8080

spring:
  application:
    name: purdue-comm-gateway
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: https://www.aaa.com
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
            - TokenCheck
            - name: Hystrix
              args:
                name: authHystrixCommand
                fallbackUri: forward:/hystrixTimeout
            - name: Retry
              args:
                retries: 3
                status: 404
                statusSeries: 500
                method: GET

        - id: post_route
          uri: https://www.baidu.com
          predicates:
            - Path=/post/**
          filters:
            - StripPrefix=1
            - TokenCheck
            - name: Hystrix
              args:
                name: authHystrixCommand
                fallbackUri: forward:/hystrixTimeout
            - name: Retry
              args:
                retries: 3
                status: 404
                statusSeries: 500
                method: GET

        - id: comment_route
          uri: https://www.baidu.com
          predicates:
            - Path=/comment/**
          filters:
            - StripPrefix=1
            - TokenCheck
            - name: Hystrix
              args:
                name: authHystrixCommand
                fallbackUri: forward:/hystrixTimeout
            - name: Retry
              args:
                retries: 3
                status: 404
                statusSeries: 500
                method: GET

  flyway:
#    locations: classpath:db/migration # 指定sql文件存放的目录
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
  datasource: ## 其他参数就不配置了
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://172.17.0.2:3306/auth_user?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: Imapeople1
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    # 使用数据库自增主键值
    use-generated-keys: true
    # 使用列别名替换列名
    use-column-label: true
    # 开启驼峰命令转换
    map-underscore-to-camel-case: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mybatis/mapper/*Mapper.xml